name: Safari
version: "0.0.1"
api: 1.0.0
author: "me@souris.cloud"
main: cloud.souris.aytos.mc.safari.SafariPlugin
commands:
  safari:
    description: Safari Command
    usage: "/safari"
    permission: sourismc.safari.command.safari
  npc:
    description: Safari NPC Command
    usage: "/npc spawn [jmeno_npc]"
    permission: sourismc.safari.command.npc
  xtime:
    description: Safari Command
    usage: "/xtime"
    permission: sourismc.safari.command.safari
  xxtime:
    description: Safari Command
    usage: "/xxtime"
    permission: sourismc.safari.command.safari
permissions:
  sourismc.safari.command.safari:
    description: "Povolit spusteni safari commandu"
    default: true
  sourismc.safari.command.npc:
    description: "Povolit spusteni safari NPC commandu"
    default: true