name: Safari
version: "0.0.1"
api: 1.0.0
author: "me@souris.cloud"
main: cloud.souris.aytos.mc.safari.SafariPlugin
commands:
  safari:
    description: Safari Command
    usage: "/safari"
    permission: sourismc.safari.command.safari
permissions:
  sourismc.safari.command.safari:
    description: "Povolit spusteni safari commandu"
    default: true