name: Safari Maven CI
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn --batch-mode install
      - name: Stage artifact with libs for upload
        run: mkdir staging && cp target/safari.jar staging && cp lib/*.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: safari-plugin-bundle
          path: staging
      - name: Copy files over SCP into Aytos
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AYTOS_SSH_HOST }}
          port: ${{ secrets.AYTOS_SSH_PORT }}
          username: ${{ secrets.AYTOS_SSH_USER }}
          key: ${{ secrets.AYTOS_SSH_SECRET }}
          source: "staging/*.jar"
          target: "/srv/mc/nukkit/plugins/"
          strip_components: 1
