name: Safari Maven CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created
jobs:
  prepare-libs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Stage external Libraries
        run: mkdir staging && cp lib/*.jar staging
      - name: Upload staged libraries as artifact
        uses: actions/upload-artifact@v2
        with:
          name: safari-dep-libs
          path: staging
  build-safari:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn --batch-mode install
      - name: Stage plugin with libs for upload bundle artifact
        run: mkdir staging && cp target/safari.jar staging && cp lib/*.jar staging
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v2
        with:
          name: safari-plugin
          path: staging/safari.jar
      - name: Upload bundle artifact
        uses: actions/upload-artifact@v2
        with:
          name: safari-plugin-bundle
          path: staging
  deploy-aytos-nukkit:
    runs-on: ubuntu-20.04
    needs: build-safari
    steps:
      - name: Download bundle artifact
        uses: actions/download-artifact@v2
        with:
          name: safari-plugin-bundle
      - name: Copy files over SCP into Aytos
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AYTOS_SSH_HOST }}
          port: ${{ secrets.AYTOS_SSH_PORT }}
          username: ${{ secrets.AYTOS_SSH_USER }}
          key: ${{ secrets.AYTOS_SSH_SECRET }}
          source: "*.jar"
          target: "/srv/mc/nukkit/plugins/"
